"""validation confidence duplicates

Revision ID: b4c54979d60d
Revises: fb10f328ef7d
Create Date: 2026-10-02 07:10:25.874930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4c54979d60d'
down_revision: Union[str, Sequence[str], None] = 'fb10f328ef7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_detection_rules',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.Enum('exact_file', 'invoice_number_supplier', 'multi_field', 'similarity', name='duplicate_rule_type'), nullable=False),
    sa.Column('fields', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_duplicate_detection_rules_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_detection_rules'))
    )
    op.create_index(op.f('ix_duplicate_detection_rules_workspace_id'), 'duplicate_detection_rules', ['workspace_id'], unique=False)
    op.create_table('confidence_threshold_versions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('high_min', sa.Float(), nullable=False),
    sa.Column('medium_min', sa.Float(), nullable=False),
    sa.Column('review_fields', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_confidence_threshold_versions_created_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confidence_threshold_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_confidence_threshold_versions_version'))
    )
    op.create_index('uq_confidence_thresholds_active', 'confidence_threshold_versions', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('duplicate_match_results',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('matched_invoice_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.Enum('no_match', 'potential_duplicate', 'confirmed_duplicate', 'review_required', name='duplicate_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('matched_fields', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('decision', sa.Enum('pending', 'kept_both', 'marked_duplicate', 'canceled', name='duplicate_decision'), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_duplicate_match_results_decided_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_duplicate_match_results_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['invoices.id'], name=op.f('fk_duplicate_match_results_matched_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['duplicate_detection_rules.id'], name=op.f('fk_duplicate_match_results_rule_id_duplicate_detection_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_duplicate_match_results_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_match_results'))
    )
    op.create_index('ix_duplicate_matches_invoice', 'duplicate_match_results', ['invoice_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('rules_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('passed', 'warning', 'needs_review', 'failed', name='validation_status'), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_validation_results_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_validation_results_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    op.create_index('ix_validation_results_invoice', 'validation_results', ['invoice_id', 'created_at'], unique=False)
    op.add_column('invoices', sa.Column('reviewed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('edited_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('invoices', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('validation_status', sa.String(length=16), nullable=True))
    op.add_column('invoices', sa.Column('validation_result_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('confidence_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('duplicate_status', sa.String(length=24), server_default='no_match', nullable=False))
    op.add_column('invoices', sa.Column('duplicate_of_invoice_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('norm_invoice_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('supplier_name', sa.String(length=300), nullable=True))
    op.add_column('invoices', sa.Column('norm_supplier_name', sa.String(length=300), nullable=True))
    op.add_column('invoices', sa.Column('supplier_tax_id', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=300), nullable=True))
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('invoices', sa.Column('grand_total', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('total_tax', sa.Numeric(precision=16, scale=2), nullable=True))
    op.create_index('ix_invoices_ws_date', 'invoices', ['workspace_id', 'invoice_date'], unique=False)
    op.create_index('ix_invoices_ws_norm_number', 'invoices', ['workspace_id', 'norm_invoice_number'], unique=False)
    op.create_index('ix_invoices_ws_supplier_tax', 'invoices', ['workspace_id', 'supplier_tax_id'], unique=False)
    op.create_foreign_key(op.f('fk_invoices_approved_by_user_id_users'), 'invoices', 'users', ['approved_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoices_approved_by_user_id_users'), 'invoices', type_='foreignkey')
    op.drop_index('ix_invoices_ws_supplier_tax', table_name='invoices')
    op.drop_index('ix_invoices_ws_norm_number', table_name='invoices')
    op.drop_index('ix_invoices_ws_date', table_name='invoices')
    op.drop_column('invoices', 'total_tax')
    op.drop_column('invoices', 'grand_total')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'customer_name')
    op.drop_column('invoices', 'supplier_tax_id')
    op.drop_column('invoices', 'norm_supplier_name')
    op.drop_column('invoices', 'supplier_name')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'invoice_date')
    op.drop_column('invoices', 'norm_invoice_number')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'duplicate_of_invoice_id')
    op.drop_column('invoices', 'duplicate_status')
    op.drop_column('invoices', 'confidence_summary')
    op.drop_column('invoices', 'validation_result_id')
    op.drop_column('invoices', 'validation_status')
    op.drop_column('invoices', 'approved_by_user_id')
    op.drop_column('invoices', 'approved_at')
    op.drop_column('invoices', 'reviewed_at')
    op.drop_column('invoices', 'edited_fields')
    op.drop_column('invoices', 'reviewed_data')
    op.drop_index('ix_validation_results_invoice', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index('ix_duplicate_matches_invoice', table_name='duplicate_match_results')
    op.drop_table('duplicate_match_results')
    op.drop_index('uq_confidence_thresholds_active', table_name='confidence_threshold_versions', postgresql_where=sa.text('is_active'))
    op.drop_table('confidence_threshold_versions')
    op.drop_index(op.f('ix_duplicate_detection_rules_workspace_id'), table_name='duplicate_detection_rules')
    op.drop_table('duplicate_detection_rules')
    # ### end Alembic commands ###
    for enum_name in (
        "validation_status", "duplicate_rule_type", "duplicate_status", "duplicate_decision",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
