"""invoices files batches jobs

Revision ID: f2a5eb74261c
Revises: 52f26206b2eb
Create Date: 2026-10-02 06:28:01.192548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2a5eb74261c'
down_revision: Union[str, Sequence[str], None] = '52f26206b2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('web', 'api', name='batch_source'), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_batches_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_batches_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_index('ix_batches_ws_created', 'batches', ['workspace_id', 'created_at'], unique=False)
    op.create_table('invoice_files',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('original', 'derived', name='file_kind'), nullable=False),
    sa.Column('parent_file_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_file_id'], ['invoice_files.id'], name=op.f('fk_invoice_files_parent_file_id_invoice_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_invoice_files_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_invoice_files_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_invoice_files_storage_key'))
    )
    op.create_index('ix_invoice_files_ws_sha256', 'invoice_files', ['workspace_id', 'sha256'], unique=False)
    op.create_table('invoices',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('processing_file_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'queued', 'processing', 'extracted', 'validation_warning', 'needs_review', 'approved', 'exported', 'failed', 'canceled', 'archived', name='invoice_status'), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('extraction_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credit_consumed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_invoices_batch_id_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['invoice_files.id'], name=op.f('fk_invoices_file_id_invoice_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processing_file_id'], ['invoice_files.id'], name=op.f('fk_invoices_processing_file_id_invoice_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_invoices_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_invoices_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_batch_id'), 'invoices', ['batch_id'], unique=False)
    op.create_index('ix_invoices_ws_created', 'invoices', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_invoices_ws_status', 'invoices', ['workspace_id', 'status'], unique=False)
    op.create_table('batch_items',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('archive_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('accepted', 'rejected', 'duplicate', name='batch_item_status'), nullable=False),
    sa.Column('rejection_code', sa.String(length=64), nullable=True),
    sa.Column('rejection_message', sa.String(length=300), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('duplicate_of_invoice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_items_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_invoice_id'], ['invoices.id'], name=op.f('fk_batch_items_duplicate_of_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_batch_items_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_batch_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_items'))
    )
    op.create_index(op.f('ix_batch_items_batch_id'), 'batch_items', ['batch_id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('initial', 'reprocess', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'succeeded', 'failed', 'canceled', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.String(length=2000), nullable=True),
    sa.Column('attempt_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_extraction_jobs_batch_id_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_extraction_jobs_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_admin_id'], ['admin_users.id'], name=op.f('fk_extraction_jobs_requested_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_extraction_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_jobs'))
    )
    op.create_index(op.f('ix_extraction_jobs_batch_id'), 'extraction_jobs', ['batch_id'], unique=False)
    op.create_index('ix_extraction_jobs_claim', 'extraction_jobs', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_invoice_id'), 'extraction_jobs', ['invoice_id'], unique=False)
    op.create_index('ix_extraction_jobs_ws_status', 'extraction_jobs', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_extraction_jobs_active_per_invoice', 'extraction_jobs', ['invoice_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_extraction_jobs_active_per_invoice', table_name='extraction_jobs', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.drop_index('ix_extraction_jobs_ws_status', table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_invoice_id'), table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_claim', table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_batch_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_batch_items_batch_id'), table_name='batch_items')
    op.drop_table('batch_items')
    op.drop_index('ix_invoices_ws_status', table_name='invoices')
    op.drop_index('ix_invoices_ws_created', table_name='invoices')
    op.drop_index(op.f('ix_invoices_batch_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_invoice_files_ws_sha256', table_name='invoice_files')
    op.drop_table('invoice_files')
    op.drop_index('ix_batches_ws_created', table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
    for enum_name in (
        "invoice_status", "job_status", "job_kind", "batch_source",
        "batch_item_status", "file_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
