"""ai providers models prompts calls

Revision ID: fb10f328ef7d
Revises: f2a5eb74261c
Create Date: 2026-10-02 06:56:12.042780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb10f328ef7d'
down_revision: Union[str, Sequence[str], None] = 'f2a5eb74261c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_providers',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_providers')),
    sa.UniqueConstraint('code', name=op.f('uq_model_providers_code'))
    )
    op.create_table('prompt_versions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_prompt_versions_created_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_prompt_versions_name'))
    )
    op.create_index('uq_prompt_versions_active', 'prompt_versions', ['name'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('provider_credentials',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('secret_hint', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], name=op.f('fk_provider_credentials_created_by_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], name=op.f('fk_provider_credentials_provider_id_model_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials'))
    )
    op.create_index(op.f('ix_provider_credentials_provider_id'), 'provider_credentials', ['provider_id'], unique=False)
    op.create_table('model_configurations',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_on', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('input_price_per_million', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('output_price_per_million', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['provider_credentials.id'], name=op.f('fk_model_configurations_credential_id_provider_credentials'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], name=op.f('fk_model_configurations_provider_id_model_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configurations'))
    )
    op.create_table('ai_calls',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('plan_code', sa.String(length=64), nullable=True),
    sa.Column('model_configuration_id', sa.UUID(), nullable=True),
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('route_position', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_class', sa.String(length=32), nullable=True),
    sa.Column('error_detail', sa.String(length=1000), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], name=op.f('fk_ai_calls_job_id_extraction_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_configuration_id'], ['model_configurations.id'], name=op.f('fk_ai_calls_model_configuration_id_model_configurations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_ai_calls_prompt_version_id_prompt_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ai_calls_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_calls'))
    )
    op.create_index('ix_ai_calls_created', 'ai_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_calls_job_id'), 'ai_calls', ['job_id'], unique=False)
    op.create_index('ix_ai_calls_model_created', 'ai_calls', ['model_name', 'created_at'], unique=False)
    op.create_index('ix_ai_calls_ws_created', 'ai_calls', ['workspace_id', 'created_at'], unique=False)
    op.add_column('extraction_jobs', sa.Column('provider_code', sa.String(length=64), nullable=True))
    op.add_column('extraction_jobs', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('extraction_jobs', sa.Column('model_configuration_id', sa.UUID(), nullable=True))
    op.add_column('extraction_jobs', sa.Column('prompt_version_id', sa.UUID(), nullable=True))
    op.add_column('extraction_jobs', sa.Column('extraction_schema_version', sa.String(length=16), nullable=True))
    op.add_column('extraction_jobs', sa.Column('confidence_method', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('extraction_job_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'extraction_job_id')
    op.drop_column('extraction_jobs', 'confidence_method')
    op.drop_column('extraction_jobs', 'extraction_schema_version')
    op.drop_column('extraction_jobs', 'prompt_version_id')
    op.drop_column('extraction_jobs', 'model_configuration_id')
    op.drop_column('extraction_jobs', 'model_name')
    op.drop_column('extraction_jobs', 'provider_code')
    op.drop_index('ix_ai_calls_ws_created', table_name='ai_calls')
    op.drop_index('ix_ai_calls_model_created', table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_job_id'), table_name='ai_calls')
    op.drop_index('ix_ai_calls_created', table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_table('model_configurations')
    op.drop_index(op.f('ix_provider_credentials_provider_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index('uq_prompt_versions_active', table_name='prompt_versions', postgresql_where=sa.text('is_active'))
    op.drop_table('prompt_versions')
    op.drop_table('model_providers')
    # ### end Alembic commands ###
