"""plans subscriptions credits usage

Revision ID: 52f26206b2eb
Revises: 963c12462c6c
Create Date: 2026-10-02 06:12:20.569182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52f26206b2eb'
down_revision: Union[str, Sequence[str], None] = '963c12462c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credits > 0', name=op.f('ck_credit_packages_positive_credits')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_credit_packages_non_negative_price')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_packages'))
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('included_credits', sa.Integer(), nullable=False),
    sa.Column('entitlements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('included_credits >= 0', name=op.f('ck_plans_non_negative_credits')),
    sa.CheckConstraint('monthly_price >= 0 AND annual_price >= 0', name=op.f('ck_plans_non_negative_price')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_index('uq_plans_single_default', 'plans', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('credit_accounts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('period_balance', sa.Integer(), nullable=False),
    sa.Column('extra_balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_balance >= 0 AND extra_balance >= 0', name=op.f('ck_credit_accounts_non_negative')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_credit_accounts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_credit_accounts'))
    )
    op.create_table('subscriptions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'expired', name='subscription_status'), nullable=False),
    sa.Column('billing_interval', sa.Enum('month', 'year', name='billing_interval'), nullable=False),
    sa.Column('source', sa.Enum('system', 'admin', 'gateway', name='subscription_source'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_subscriptions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=False)
    op.create_index('uq_subscriptions_current_per_workspace', 'subscriptions', ['workspace_id'], unique=True, postgresql_where=sa.text("status IN ('trialing', 'active', 'past_due')"))
    op.create_table('credit_ledger',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('allocation', 'expiry', 'purchase', 'grant', 'revoke', 'adjustment', 'consumption', 'reversal', name='ledger_entry_type'), nullable=False),
    sa.Column('bucket', sa.Enum('period', 'extra', 'overage', name='credit_bucket'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('actor_admin_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], name=op.f('fk_credit_ledger_actor_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_credit_ledger_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_credit_ledger_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_credit_ledger_idempotency_key'))
    )
    op.create_index('ix_credit_ledger_ws_created', 'credit_ledger', ['workspace_id', 'created_at'], unique=False)
    op.create_table('usage_records',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_usage_records_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_usage_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_usage_records_idempotency_key'))
    )
    op.create_index('ix_usage_records_ws_metric_created', 'usage_records', ['workspace_id', 'metric', 'created_at'], unique=False)
    op.add_column('workspaces', sa.Column('entitlement_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'entitlement_overrides')
    op.drop_index('ix_usage_records_ws_metric_created', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_credit_ledger_ws_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index('uq_subscriptions_current_per_workspace', table_name='subscriptions', postgresql_where=sa.text("status IN ('trialing', 'active', 'past_due')"))
    op.drop_index(op.f('ix_subscriptions_workspace_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('credit_accounts')
    op.drop_index('uq_plans_single_default', table_name='plans', postgresql_where=sa.text('is_default'))
    op.drop_table('plans')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
    for enum_name in (
        "subscription_status", "billing_interval", "subscription_source",
        "ledger_entry_type", "credit_bucket",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
